### PR TITLE
Fix exhaustive deps

### PR DESCRIPTION
**Pull request by dyegolara**
- Turn off react-hooks/exhaustive-deps rule

### CODE REVIEW

**Comment by aegre** [comment]
I'm not sure about removing the it, it's annoying for some case but I think most of the time it could be helpful

**Comment by dyegolara** [comment]
@aegre @jmz7v 
I dont think this is a protection.
Its better to not have it because if you miss a dependency, the useEffect will trigger less often.
If we had it enabled, the auto correct or the precommit hook will add the dependencies and your useEffect will trigger on any change of the dependencies, including functions used, which usually are different on each render causing an infinite loop

**Comment by aegre** [comment]
I feel like the rules are there because it's how the hooks are supposed to work, if we need to remove them means that we are doing something wrong imo, the only thing I found strange of this rule is when you want the hook to run only the first time it removes the empty array from depencies and the hook runs more than once

**Comment by dyegolara** [comment]
Maybe we have not found a more correct way to use the dependencies or the hooks flow yet.
But right now this is a potential risk in our apps that can slip into our apps very silently (precommit hook). 
Until we find a pattern that let us do react hooks in the right way, lets turn this off.

**Pull request merged**
